name: Run Amazon Affiliate Bot

on:
  schedule:
    - cron: '30 3 * * *'     # Daily 9:00 AM IST
    - cron: '30 15 * * *'    # Daily 9:00 PM IST
  workflow_dispatch:
    inputs:
      day:
        description: 'Day of the week (e.g. Monday)'
        required: false
        default: ''
      time_of_day:
        description: 'Time of day: morning or evening'
        required: false
        default: ''

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install system dependencies for Playwright Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-4-1 \
            libgraphene-1.0-0 \
            libvpx9 \
            libevent-2.1-7 \
            libopus0 \
            gstreamer1.0-libav \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            gstreamer1.0-plugins-bad \
            gstreamer1.0-plugins-ugly \
            gstreamer1.0-tools \
            gstreamer1.0-x \
            libsecret-1-0 \
            libhyphen0 \
            libgstreamer-plugins-base1.0-0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install firefox

      - name: Run main.py with optional args
        run: |
          if [ -z "${{ github.event.inputs.day }}" ]; then
            echo "🟢 No manual inputs — running with system time"
            python main.py
          else
            echo "🟡 Manual input provided — running for ${{ github.event.inputs.day }} ${{ github.event.inputs.time_of_day }}"
            python main.py "${{ github.event.inputs.day }}" "${{ github.event.inputs.time_of_day }}"
          fi
