name: Amazon Affiliate Bot - Firefox Scrape

on:
  push:
    branches:
      - main

  schedule:
    - cron: "03 3,15 * * *" # Run at 9:03 AM and 9:03 PM IST (3:33 and 15:33 UTC)

  workflow_dispatch:
    inputs:
      day:
        description: 'Day of the week (e.g., Monday, Tuesday...)'
        required: false
        default: ''
      time_of_day:
        description: 'Time of day (morning/evening)'
        required: false
        default: ''

jobs:
  scrape-firefox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies for Firefox Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-4-1 libdbus-glib-1-2 libxt6 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libasound2 \
            libpangocairo-1.0-0 libcups2 libdrm2 libxshmfence1 libnspr4 libnss3 libwayland-client0 \
            libwayland-cursor0 libwayland-egl1 libegl1 libx11-xcb1 libxcb1 libxfixes3 libxrender1 libxext6 libexpat1

      - name: Remove Playwright cache (force fresh install)
        run: rm -rf ~/.cache/ms-playwright

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Firefox browser
        run: python -m playwright install firefox

      - name: Run Affiliate Bot
        run: |
          echo "🟡 Manual input provided — running for ${{ inputs.day }} ${{ inputs.time_of_day }}"
          python main.py --day "${{ inputs.day }}" --time_of_day "${{ inputs.time_of_day }}"
