name: Amazon Affiliate Bot

on:
  schedule:
    - cron: '30 3,15 * * *'  # Runs daily at 9:00 AM and 9:00 PM IST (3:30 UTC & 15:30 UTC)
  workflow_dispatch:
    inputs:
      day:
        description: 'Day of the week (e.g., Monday)'
        required: false
        default: ''
      time_of_day:
        description: 'Time of day (morning/evening)'
        required: false
        default: ''

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run main.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GITHUB_ACTIONS: true
        run: |
          python main.py "${{ github.event.inputs.day }}" "${{ github.event.inputs.time_of_day }}"
