name: Amazon Affiliate Bot - Firefox Scrape

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      day:
        description: 'Day of the week (e.g., Monday)'
        required: false
        default: ''
      time_of_day:
        description: 'Time of day (morning/evening)'
        required: false
        default: ''

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install system dependencies for Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-4-1 libdbus-glib-1-2 libxt6 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libasound2t64 libpangocairo-1.0-0 libcups2 libdrm2 libxshmfence1 libnspr4 libnss3 libwayland-client0 libwayland-cursor0 libwayland-egl1 libegl1 libx11-xcb1 libxcb1 libxfixes3 libxrender1 libxext6 libexpat1

      - name: Clean Playwright cache
        run: rm -rf ~/.cache/ms-playwright

      - name: Install Python dependencies and Playwright browser
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install firefox

      - name: Run affiliate bot script
        run: |
          if [ -z "${{ github.event.inputs.day }}" ]; then
            echo "🟢 Running with system time"
            python main.py
          else
            echo "🟡 Manual input: ${{ github.event.inputs.day }} ${{ github.event.inputs.time_of_day }}"
            python main.py --day "${{ github.event.inputs.day }}" --time_of_day "${{ github.event.inputs.time_of_day }}"
          fi
