name: Run Amazon Affiliate Bot (Firefox)

on:
  schedule:
    - cron: '30 3 * * *'     # 9:00 AM IST
    - cron: '30 15 * * *'    # 9:00 PM IST
  workflow_dispatch:
    inputs:
      day:
        description: 'Day of the week (e.g. Monday)'
        required: false
        default: ''
      time_of_day:
        description: 'Time of day: morning or evening'
        required: false
        default: ''

jobs:
  run:
    runs-on: ubuntu-22.04

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install system dependencies for Firefox Playwright
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-0 libxss1 libasound2 libdbus-glib-1-2 libxt6 libxcomposite1 \
            libxdamage1 libxrandr2 libgbm1 libnss3 libatk1.0-0 libcups2 \
            libdrm2 libxshmfence1 libnspr4 libx11-xcb1 libxcb1 libxfixes3 \
            libxrender1 libxext6 libexpat1 libwayland-client0 libwayland-cursor0 libwayland-egl1 \
            fonts-liberation libappindicator3-1 xdg-utils wget

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright (Firefox only)
        run: |
          python -m playwright install --with-deps

      - name: Run main.py with optional inputs
        run: |
          if [ -z "${{ github.event.inputs.day }}" ]; then
            echo "🟢 No manual inputs — running with system time"
            python main.py
          else
            echo "🟡 Manual input provided — running for ${{ github.event.inputs.day }} ${{ github.event.inputs.time_of_day }}"
            python main.py "${{ github.event.inputs.day }}" "${{ github.event.inputs.time_of_day }}"
          fi
